In [1]:
import pandas as pd
import numpy as np
import datetime
import talib as ta
import mplfinance as mpf
import matplotlib.pyplot as plt
from iexfinance.stocks import get_historical_data

In [2]:
# 解决matplotlib无法显示中文的问题
plt.rcParams['font.family'] = ['sans-serif']
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False
%matplotlib inline

In [3]:
start_date = datetime.date(2021,1,1)
api_key = 'sk_6da55e0040724dae968ee05db3cb1974'
df = get_historical_data('MSFT',output_format='pandas',token=api_key, start=start_date)
df.head()

,close,high,low,open,symbol,volume,id,key,subkey,updated,...,uLow,uVolume,fOpen,fClose,fHigh,fLow,fVolume,label,change,changePercent
2021-01-04,217.69,223,214.81,222.53,MSFT,37130139,HISTORICAL_PRICES,MSFT,,1653420604000,...,214.81,37130139,219.7131,214.9344,220.1772,212.0908,37130139,"Jan 4, 21",-4.73,-0.0213
2021-01-05,217.9,218.52,215.7,217.26,MSFT,23822953,HISTORICAL_PRICES,MSFT,,1653420249000,...,215.7,23822953,214.5098,215.1417,215.7539,212.9696,23822953,"Jan 5, 21",0.21,0.001
2021-01-06,212.25,216.4899,211.94,212.17,MSFT,35930653,HISTORICAL_PRICES,MSFT,,1653420401000,...,211.94,35930653,209.4842,209.5632,213.7495,209.2572,35930653,"Jan 6, 21",-5.65,-0.0259
2021-01-07,218.29,219.34,213.71,214.04,MSFT,27694480,HISTORICAL_PRICES,MSFT,,1653420249000,...,213.71,27694480,211.3306,215.5268,216.5635,211.0048,27694480,"Jan 7, 21",6.04,0.0285
2021-01-08,219.62,220.58,217.0261,218.68,MSFT,22956206,HISTORICAL_PRICES,MSFT,,1653420556000,...,217.0261,22956206,215.9118,216.8399,217.7878,214.2789,22956206,"Jan 8, 21",1.33,0.0061

In [4]:
# Now we need to get open, close, high, low price seperately
open_price = np.array(df['open'],dtype='f8')
close_price = np.array(df['close'],dtype='f8')
high_price = np.array(df['high'],dtype='f8')
low_price = np.array(df['low'],dtype='f8')
print(low_price)

[214.81   215.7    211.94   213.71   217.0261 216.73   213.3202 213.9266
 212.74   212.03   212.63   217.2908 222.42   225.8    224.22   230.08
 230.14   235.09   231.35   232.43   238.69   239.26   240.37   240.42
 240.81   241.38   240.89   242.15   242.73   242.92   240.94   240.86
 240.18   232.4    228.73   229.     227.88   229.54   233.15   233.45
 227.26   224.26   226.46   227.13   231.67   232.04   234.31   233.23
 231.81   235.94   233.23   230.33   229.3496 230.14   237.07   235.32
 231.57   231.55   231.88   231.1    232.39   238.0501 242.7    246.88
 247.19   252.     252.44   254.62   256.83   255.16   257.73   257.6014
 257.821  256.84   257.25   255.64   257.27   260.17   260.12   252.95
 249.     249.6    251.12   245.76   245.82   244.69   251.17   247.12
 242.57   238.07   241.42   245.49   243.52   242.9    238.6    243.86
 244.74   247.51   250.82   250.75   249.25   249.56   246.96   245.84
 243.     247.51   249.81   252.51   253.21   253.67   256.61   256.8
 257.68   254.42   256.01   258.75   257.92   262.4    264.43   265.47
 264.76   265.91   267.98   269.6043 269.6    272.5    274.3    277.15
 274.87   275.32   276.58   277.39   280.55   279.83   279.46   274.45
 276.26   277.29   283.42   286.5    286.642  282.95   283.8303 286.08
 283.91   283.74   284.     284.65   286.1    287.6238 287.81   285.2
 285.86   286.34   289.3    290.02   291.08   290.27   288.64   298.06
 301.85   302.0035 300.42   298.95   296.83   301.06   301.5    301.49
 300.18   300.26   298.2    297.4651 297.     295.38   294.08   298.1
 301.82   300.76   299.53   289.52   294.07   294.51   297.5339 296.93
 292.9449 282.75   283.01   281.62   281.29   280.25   284.0464 285.5093
 293.92   293.76   292.745  292.35   293.49   297.83   300.5191 302.69
 307.22   306.11   306.36   307.8    306.46   308.5967 316.     321.3601
 323.9    326.37   330.     330.65   329.51   334.4217 334.44   334.53
 329.92   330.51   333.79   334.034  335.51   338.     337.12   342.2
 339.55   333.56   333.911  328.12   334.74   328.99   329.39   327.8028
 318.03   319.23   330.1    330.8    332.12   334.79   339.08   324.11
 324.5    323.02   317.25   317.57   319.8    325.75   332.73   335.43
 340.32   339.68   338.82   335.85   329.78   326.12   315.98   311.49
 310.09   304.69   309.89   317.08   304.     303.75   301.74   302.7
 301.14   295.61   276.05   285.17   293.03   297.93   294.45   306.37
 305.1293 308.88   299.96   299.97   299.9    299.95   307.39   300.7
 294.22   291.35   297.02   293.68   290.     286.305  284.5    280.1
 271.52   291.655  293.     292.15   293.698  294.05   287.165  278.53
 270.     280.78   280.58   279.43   275.82   278.725  283.2    289.37
 292.73   294.9    298.77   297.7201 298.315  299.2855 304.33   309.05
 311.58   307.89   305.54   309.71   309.87   296.71   296.35   296.28
 285.     280.49   281.3    279.32   278.34   278.41   285.3702 280.06
 273.38   270.77   270.     279.16   281.4562 276.5    276.22   280.15
 276.73   274.34   271.27   263.32   265.07   259.3    250.02   255.35
 255.78   262.46   252.77   251.88   246.44   253.43   253.5    257.125
 261.4294 267.56  ]

In [5]:
# 早晨之星 Morning Star 符合条件的标记为100 不符合条件的标记为0
ms = ta.CDLMORNINGSTAR(open_price, high_price, low_price, close_price)
# 打印非零的值
print(ms[ms!=0])
ms[:100]

[]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
signal = np.where(ms==100,close_price,np.nan)
signal[:100]

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [7]:
if len(ms[ms!=0]) > 0:
    add_plot = mpf.make_addplot(signal, type='scatter', markersize=100, marker='^', color='b', secondary_y=False)
    # 作图
    mpf.plot(df,type='candle',addplot=add_plot, style=s, figsize=(16,10))
else:
    print('所选的行情中没有出现早晨之星')

所选的行情中没有出现早晨之星

## 三只乌鸦

In [8]:
three_crows = ta.CDL3BLACKCROWS(open_price, high_price, low_price, close_price)
three_crows[three_crows!=0]

array([], dtype=int32)

## RSI

In [11]:
#rsi_result = ta.momentum.RSIIndicator(close_price,14).rsi()
ta.RSI(close_price,14)

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan, 64.83709273,
       67.30776125, 67.80371027, 72.54820776, 61.30302651, 67.32142719,
       67.11677258, 69.59792544, 68.02982848, 68.17801442, 68.40215184,
       69.51549863, 67.63989604, 69.21247172, 69.68743771, 66.82313494,
       67.38273398, 66.39379916, 59.88383522, 48.21989217, 46.35354436,
       48.56656197, 40.71057768, 46.403192  , 52.94754423, 48.64136857,
       41.22078812, 40.34882837, 47.38198313, 42.69546053, 50.67073396,
       49.10434641, 54.3657284 , 52.64842364, 51.4561045 , 54.85306316,
       53.91437423, 45.92994785, 45.50506595, 52.68949017, 54.51024769,
       51.65570715, 47.69700702, 52.85949395, 51.22850822, 46.96232553,
       51.94577823, 58.92281554, 64.57905406, 62.89957144, 64.57241329,
       67.18877468, 69.09633952, 69.14092591, 71.07352206, 66.06518178,
       69.2150204 , 70.16094697, 66.60606392, 65.74509171, 67.90457537,
       61.74333342, 65.65972713, 66.03604863, 66.45176672, 53.91363259,
       51.0442182 , 50.57756169, 50.09925903, 44.35403279, 42.64591628,
       47.9746914 , 51.99687839, 44.78517543, 43.61310967, 35.91049072,
       42.05374083, 48.77215722, 45.47821417, 43.2537987 , 43.31067603,
       48.02342188, 46.40369422, 53.61828855, 54.71818194, 54.37838863,
       51.13699547, 51.66362999, 48.21512945, 48.06359497, 45.60910378,
       53.73783003, 57.77768894, 55.6296319 , 57.04434747, 61.7448413 ,
       62.53115997, 64.92042449, 61.6801236 , 59.6272231 , 64.23209394,
       61.09797824, 65.09113204, 68.24988962, 67.71149219, 69.28278155,
       65.24712422, 69.48777734, 72.13961463, 70.90153505, 71.63547903,
       77.02842055, 77.03619238, 78.79037999, 72.22094732, 72.728267  ,
       71.06188699, 74.74113245, 76.10862428, 72.04538853, 71.27016506,
       61.71744753, 64.85113405, 67.43594719, 72.41445404, 75.42740911,
       73.9006828 , 67.90802073, 67.16029066, 67.49752589, 63.50917057,
       63.28123558, 66.58207263, 64.91532463, 69.034515  , 68.86096009,
       65.52010897, 60.25457833, 61.16160869, 65.86599046, 70.02250159,
       72.12666618, 67.68287791, 61.38586167, 69.29340264, 75.9565739 ,
       76.16935157, 71.4056454 , 69.98915403, 63.49586782, 64.26616067,
       68.64337884, 64.8625883 , 64.75028715, 63.1489611 , 63.1242376 ,
       60.66860332, 60.72002821, 53.31332482, 49.90272369, 52.61604014,
       57.97769604, 65.52463869, 66.04685199, 54.21758703, 45.15073449,
       46.02334774, 52.21301242, 53.69554059, 53.31385018, 44.84569286,
       33.17762998, 34.01097728, 32.1404547 , 43.65936451, 37.88210822,
       45.2423986 , 50.14074526, 51.99075761, 51.99075761, 51.20559774,
       49.45428917, 53.77966052, 60.59739999, 61.96707846, 64.75079863,
       65.57884219, 64.16285838, 67.27192901, 64.39829501, 62.54604606,
       64.65087271, 74.7360342 , 75.41843144, 79.1542834 , 75.33811437,
       77.30706097, 77.74970991, 78.98764713, 78.25740508, 78.77459225,
       76.58082041, 66.67824763, 68.0849078 , 71.49549553, 70.27018832,
       72.91572224, 72.13203959, 73.8035896 , 75.17589819, 68.30658564,
       64.16754783, 64.41595617, 50.83552293, 58.74528487, 51.0573903 ,
       50.45694524, 49.72835181, 42.4740496 , 46.59159138, 55.91964621,
       55.96708126, 53.64211591, 62.18272956, 58.33306737, 47.23956062,
       52.75942183, 44.93634739, 44.14111603, 41.35400119, 48.05509852,
       52.71470698, 53.83896377, 59.27034516, 58.13127929, 58.63072782,
       55.93114206, 52.93694156, 51.38655576, 46.07366792, 37.00710984,
       35.5172338 , 35.69566462, 35.96994996, 36.86520406, 40.98297358,
       31.82960609, 37.82482816, 33.40182237, 34.14870355, 33.13071736,
       30.02705687, 30.4553249 , 26.41942118, 35.95396831, 39.18544909,
       46.9411277 , 49.19515378, 47.42434755, 51.41191521, 42.41240655,
       46.30075401, 42.97589345, 45.99718813, 51.13343122, 45.01164918,
       40.6545076 , 40.63142486, 45.21254667, 44.55596291, 39.03630219,
       37.44151379, 37.31837268, 33.15265683, 45.69968148, 47.7074204 ,
       48.81637407, 46.08555842, 50.18105125, 47.04491435, 42.94308205,
       36.71401167, 35.17834343, 45.35430182, 43.65648395, 40.55514427,
       38.61255345, 46.72134546, 51.39534078, 51.91612604, 55.16367079,
       54.2026628 , 57.29395619, 53.65626962, 56.64653471, 56.29017846,
       60.73623953, 63.42440656, 61.92194145, 56.73900735, 57.50510228,
       61.20443099, 57.24921096, 47.96193917, 49.41415669, 46.15065256,
       38.80529885, 37.06900372, 41.93070804, 37.5532787 , 38.16900752,
       42.40566269, 43.33294126, 39.72647198, 35.80597628, 41.89890895,
       36.10643309, 46.05095708, 50.16930621, 43.42482848, 47.76491032,
       46.28490401, 51.24427372, 44.43868759, 43.15822644, 38.5267735 ,
       41.78777934, 37.85391822, 35.74825198, 39.75296609, 40.01812065,
       43.75057288, 37.70046192, 37.2907078 , 37.0233229 , 43.14677809,
       42.57911995, 44.7818721 , 47.31850302, 52.42919968])